name: Running tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn

    - name: Build and run PostgreSQL
      run: |
        docker-compose up -d

    - name: Run tests
      run: |
        yarn test:server && test:client

    - name: Stop PostgreSQL container
      run: |
        docker-compose down
